export const sampleData = {
  data: [
    {
      fieldData: {
        "%Location.CityStateZIP": "",
        "%excelexport.NumberOfFollowUpAttempts": "",
        "%ui.AdjustedDateofReferral": "02/04/2022",
        HighLightColor_examScheduling: "blue",
        HighLightColor_examqa: "",
        __ExamAddressCityStateZipCountryCommaSeparated: " United States",
        "applicantNameFirstLast.indexedCalc": "Jeremy Brown",
        creationAccountName: "jeremy@integratingmagic.io",
        creationTimeStamp: "02/04/2022 15:33:13",
        examCompanyEmployerName: "ACME",
        examDateofExam: "",
        examDeptContract: "AFCAP TO 11",
        examExamType: "Male (39-48) [MOD]",
        examJobClass: "Core Sport Leader",
        examReferralInitiatedDate: "02/04/2022",
        examSchedulingDateOfNextFollowUp: "",
        examStatus: "Quality Review",
        id: "12063779585594000000008952066428780429467",
      },
      modId: "88",
      portalData: {},
      recordId: "560372",
    },
    {
      fieldData: {
        "%Location.CityStateZIP": "",
        "%excelexport.NumberOfFollowUpAttempts": "",
        "%ui.AdjustedDateofReferral": "02/04/2022",
        HighLightColor_examScheduling: "",
        HighLightColor_examqa: "",
        __ExamAddressCityStateZipCountryCommaSeparated: " Afghanistan",
        "applicantNameFirstLast.indexedCalc": "Jeremy Brown",
        creationAccountName: "jeremy@integratingmagic.io",
        creationTimeStamp: "02/04/2022 16:57:54",
        examCompanyEmployerName: "ACME",
        examDateofExam: "",
        examDeptContract: "AFCAP TO 69",
        examExamType: "Male Food Service Worker (35-38) [MOD]",
        examJobClass: "Fitness Center Manager",
        examReferralInitiatedDate: "02/04/2022",
        examSchedulingDateOfNextFollowUp: "",
        examStatus: "Ready for Scheduling",
        id: "12063779590675000000002695066428780429467",
      },
      modId: "29",
      portalData: {},
      recordId: "560373",
    },
    {
      fieldData: {
        "%Location.CityStateZIP": "",
        "%excelexport.NumberOfFollowUpAttempts": "",
        "%ui.AdjustedDateofReferral": "02/04/2022",
        HighLightColor_examScheduling: "",
        HighLightColor_examqa: "",
        __ExamAddressCityStateZipCountryCommaSeparated: " United States",
        "applicantNameFirstLast.indexedCalc": "Jeremy Brown",
        creationAccountName: "jeremy@integratingmagic.io",
        creationTimeStamp: "02/07/2022 14:51:39",
        examCompanyEmployerName: "ACME",
        examDateofExam: "",
        examDeptContract: "ANG Cyber Ops",
        examExamType: "Occu-VAX COVID-19 Immunization",
        examJobClass: "Network Engineer (Infrastructure)",
        examReferralInitiatedDate: "02/04/2022",
        examSchedulingDateOfNextFollowUp: "",
        examStatus: "Requires Harvesting",
        id: "12063779831499000000002858274963648409633",
      },
      modId: "25",
      portalData: {},
      recordId: "560374",
    },
    {
      fieldData: {
        "%Location.CityStateZIP": "",
        "%excelexport.NumberOfFollowUpAttempts": "",
        "%ui.AdjustedDateofReferral": "02/09/2022",
        HighLightColor_examScheduling: "",
        HighLightColor_examqa: "",
        __ExamAddressCityStateZipCountryCommaSeparated: " United States",
        "applicantNameFirstLast.indexedCalc": "Jeremy Brown",
        creationAccountName: "jgill@occu-med.com",
        creationTimeStamp: "02/09/2022 12:02:29",
        examCompanyEmployerName: "ACME",
        examDateofExam: "",
        examDeptContract: "AFCAP TO 08",
        examExamType: "Male (34 and younger) [MOD]",
        examJobClass: "Customer Service Technician",
        examReferralInitiatedDate: "02/09/2022",
        examSchedulingDateOfNextFollowUp: "",
        examStatus: "Quality Review",
        id: "12063780004949000000003948066428780429467",
      },
      modId: "42",
      portalData: {},
      recordId: "560375",
    },
    {
      fieldData: {
        "%Location.CityStateZIP": "",
        "%excelexport.NumberOfFollowUpAttempts": "",
        "%ui.AdjustedDateofReferral": "02/09/2022",
        HighLightColor_examScheduling: "",
        HighLightColor_examqa: "",
        __ExamAddressCityStateZipCountryCommaSeparated: " United States",
        "applicantNameFirstLast.indexedCalc": "Michael Holmes",
        creationAccountName: "jgill@occu-med.com",
        creationTimeStamp: "02/09/2022 14:48:58",
        examCompanyEmployerName: "ACME",
        examDateofExam: "",
        examDeptContract: "AFCAP TO 08",
        examExamType: "Male (39-48) [MOD]",
        examJobClass: "Site Manager",
        examReferralInitiatedDate: "02/09/2022",
        examSchedulingDateOfNextFollowUp: "",
        examStatus: "Ready for Scheduling",
        id: "12063780014938000000013369066428780429467",
      },
      modId: "78",
      portalData: {},
      recordId: "560376",
    },
    {
      fieldData: {
        "%Location.CityStateZIP": "",
        "%excelexport.NumberOfFollowUpAttempts": "",
        "%ui.AdjustedDateofReferral": "02/10/2022",
        HighLightColor_examScheduling: "",
        HighLightColor_examqa: "",
        __ExamAddressCityStateZipCountryCommaSeparated: "",
        "applicantNameFirstLast.indexedCalc": "Amanpreet Singh",
        creationAccountName: "ccoyle@occu-med.com",
        creationTimeStamp: "02/10/2022 13:09:13",
        examCompanyEmployerName: "ACME",
        examDateofExam: "02/09/2022",
        examDeptContract: "LOGCAP V - Iraq Task Order (OCN)",
        examExamType: "Overseas COVID-19 Testing",
        examJobClass: "Hvac Mechanic",
        examReferralInitiatedDate: "02/10/2022",
        examSchedulingDateOfNextFollowUp: "",
        examStatus: "Complete",
        id: "12063780095354000000107690062645638741572",
      },
      modId: "20",
      portalData: {},
      recordId: "560377",
    },
    {
      fieldData: {
        "%Location.CityStateZIP": "",
        "%excelexport.NumberOfFollowUpAttempts": "",
        "%ui.AdjustedDateofReferral": "02/10/2022",
        HighLightColor_examScheduling: "",
        HighLightColor_examqa: "",
        __ExamAddressCityStateZipCountryCommaSeparated: "",
        "applicantNameFirstLast.indexedCalc": "Gurlal Singh ",
        creationAccountName: "ccoyle@occu-med.com",
        creationTimeStamp: "02/10/2022 13:09:22",
        examCompanyEmployerName: "ACME",
        examDateofExam: "02/09/2022",
        examDeptContract: "LOGCAP V - Iraq Task Order (OCN)",
        examExamType: "Overseas COVID-19 Testing",
        examJobClass: "Carpenter Lead",
        examReferralInitiatedDate: "02/10/2022",
        examSchedulingDateOfNextFollowUp: "",
        examStatus: "Complete",
        id: "12063780095363000000007690062645638741572",
      },
      modId: "22",
      portalData: {},
      recordId: "560378",
    },
    {
      fieldData: {
        "%Location.CityStateZIP": "",
        "%excelexport.NumberOfFollowUpAttempts": "",
        "%ui.AdjustedDateofReferral": "02/10/2022",
        HighLightColor_examScheduling: "",
        HighLightColor_examqa: "",
        __ExamAddressCityStateZipCountryCommaSeparated: "",
        "applicantNameFirstLast.indexedCalc": "Iqbal  ",
        creationAccountName: "ccoyle@occu-med.com",
        creationTimeStamp: "02/10/2022 13:09:27",
        examCompanyEmployerName: "ACME",
        examDateofExam: "02/09/2022",
        examDeptContract: "LOGCAP V - Iraq Task Order (OCN)",
        examExamType: "Overseas COVID-19 Testing",
        examJobClass: "Carpenter",
        examReferralInitiatedDate: "02/10/2022",
        examSchedulingDateOfNextFollowUp: "",
        examStatus: "Complete",
        id: "12063780095368000000107690062645638741572",
      },
      modId: "21",
      portalData: {},
      recordId: "560379",
    },
    {
      fieldData: {
        "%Location.CityStateZIP": "",
        "%excelexport.NumberOfFollowUpAttempts": "",
        "%ui.AdjustedDateofReferral": "02/09/2022",
        HighLightColor_examScheduling: "",
        HighLightColor_examqa: "",
        __ExamAddressCityStateZipCountryCommaSeparated: " United States",
        "applicantNameFirstLast.indexedCalc": "Jeremy Brown",
        creationAccountName: "krank@occu-med.com",
        creationTimeStamp: "02/10/2022 14:54:22",
        examCompanyEmployerName: "ACME",
        examDateofExam: "",
        examDeptContract: "AFCAP TO 08",
        examExamType: "Occu-VAX Stateside (Afghanistan)",
        examJobClass: "Customer Service Technician",
        examReferralInitiatedDate: "02/09/2022",
        examSchedulingDateOfNextFollowUp: "",
        examStatus: "Requires Harvesting",
        id: "12063780101663000000008827045013239605206",
      },
      modId: "13",
      portalData: {},
      recordId: "560380",
    },
    {
      fieldData: {
        "%Location.CityStateZIP": "",
        "%excelexport.NumberOfFollowUpAttempts": "",
        "%ui.AdjustedDateofReferral": "02/09/2022",
        HighLightColor_examScheduling: "",
        HighLightColor_examqa: "",
        __ExamAddressCityStateZipCountryCommaSeparated: " United States",
        "applicantNameFirstLast.indexedCalc": "Jeremy Brown",
        creationAccountName: "krank@occu-med.com",
        creationTimeStamp: "02/10/2022 14:57:07",
        examCompanyEmployerName: "ACME",
        examDateofExam: "",
        examDeptContract: "AFCAP TO 08",
        examExamType: "Occu-VAX Stateside (Afghanistan)",
        examJobClass: "Customer Service Technician",
        examReferralInitiatedDate: "02/09/2022",
        examSchedulingDateOfNextFollowUp: "",
        examStatus: "Requires Harvesting",
        id: "12063780101827000000008827045013239605206",
      },
      modId: "14",
      portalData: {},
      recordId: "560381",
    },
  ],
  dataInfo: {
    database: "CRMS_data",
    foundCount: 0,
    layout: "EXAM_SCHEDULING_EXAM",
    returnedCount: 10,
    table: "Exams",
    totalRecordCount: 10,
  },
};
